name: Cypress E2E Tests

on:
  pull_request:
    branches:
      - dev

jobs:
  cypress-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Build the application
      run: npm run build

    - name: Start the application
      run: npm start &
      env:
        CI: true

    - name: Run Cypress tests
      uses: cypress-io/github-action@v6
      with:
        wait-on: 'http://localhost:3000'
        wait-on-timeout: 60
        config-file: cypress.config.ts 
