name: Jest Integration Tests

on:
  pull_request:
    branches:
      - dev

jobs:
  run-jest-integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
        
      - name: Install dependencies
        run: npm ci

      - name: Run Jest integration tests
        run: npm run test:integration

      - name: Fail on test errors
        if: ${{ failure() }}
        run: exit 1
